# Generated by Django 6.0.7 on 2026-08-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_publisher_alter_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
