# Generated by Django 6.0.7 on 2026-08-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loan_member_loan_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
